# Generated by Django 6.0.6 on 2026-06-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disable_unsafe_seeded_admin_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['module__learning_path__order', 'module__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('cpu_count', models.PositiveSmallIntegerField(default=1)),
                ('memory_mb', models.PositiveIntegerField(default=256)),
                ('time_limit_minutes', models.PositiveIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['cpu_count', 'memory_mb', 'time_limit_minutes', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('theory', 'Theory'), ('guided_practice', 'Guided Practice'), ('sandbox', 'Sandbox'), ('challenge', 'Challenge'), ('reflection', 'Reflection'), ('assessment', 'Assessment')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.activity')),
            ],
            options={
                'ordering': ['activity__module__learning_path__order', 'activity__module__order', 'activity__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True)),
                ('passing_score', models.PositiveSmallIntegerField(default=70)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='core.activity')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.learningpath')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.learningpath')),
            ],
            options={
                'ordering': ['learning_path__order', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.module'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='core.activitystage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity_stage__activity__order', 'activity_stage__order'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='resource_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.resourceprofile'),
        ),
        migrations.AddConstraint(
            model_name='activitystage',
            constraint=models.UniqueConstraint(fields=('activity', 'stage_type'), name='unique_stage_type_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='activitystage',
            constraint=models.UniqueConstraint(fields=('activity', 'order'), name='unique_stage_order_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'learning_path'), name='unique_enrollment_per_user_path'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('learning_path', 'slug'), name='unique_module_slug_per_path'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('user', 'activity_stage'), name='unique_progress_per_user_stage'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='unique_activity_slug_per_module'),
        ),
    ]
