# Generated by Django 6.0.6 on 2026-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activity_learningpath_resourceprofile_activitystage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystage',
            name='config_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='activitystage',
            name='content_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
