# Generated by Django 6.0.6 on 2026-06-28 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitystage_config_file_activitystage_content_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('command', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('theory_content', models.TextField(blank=True)),
                ('sandbox_image', models.CharField(blank=True, default='', max_length=200)),
                ('sandbox_config', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hack_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='core.hackphase')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_labs', to=settings.AUTH_USER_MODEL)),
                ('resource_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labs', to='core.resourceprofile')),
                ('tools', models.ManyToManyField(blank=True, related_name='labs', to='core.tool')),
            ],
            options={
                'ordering': ['hack_phase__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SandboxSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, max_length=128)),
                ('server_url', models.CharField(blank=True, max_length=500)),
                ('terminal_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_sessions', to='core.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LabEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'lab'), name='unique_enrollment_per_user_lab')],
            },
        ),
        migrations.CreateModel(
            name='LabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('theory', 'Theory'), ('sandbox', 'Sandbox'), ('complete', 'Complete')], max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='core.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lab__order', 'stage'],
                'constraints': [models.UniqueConstraint(fields=('user', 'lab', 'stage'), name='unique_progress_per_user_lab_stage')],
            },
        ),
        migrations.AddConstraint(
            model_name='lab',
            constraint=models.UniqueConstraint(fields=('hack_phase', 'slug'), name='unique_lab_slug_per_phase'),
        ),
    ]
