# Generated by Django 6.0.6 on 2026-07-02 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hackphase_tool_lab_sandboxsession_labenrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('docker_image', models.CharField(blank=True, default='', max_length=200)),
                ('port', models.PositiveIntegerField(default=80)),
                ('script_module', models.CharField(blank=True, help_text='Python module path, e.g. scenario_services.sql_injection', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lab',
            name='flag',
            field=models.CharField(blank=True, help_text='The flag students must find and submit to complete the lab.', max_length=500),
        ),
        migrations.AddField(
            model_name='lab',
            name='flag_hint',
            field=models.TextField(blank=True, help_text='Hint shown when a student submits a wrong flag.'),
        ),
        migrations.AddField(
            model_name='lab',
            name='notes',
            field=models.TextField(blank=True, help_text='Student walkthrough. Use {{SERVICE_IP}} for the service container IP.'),
        ),
        migrations.AddField(
            model_name='sandboxsession',
            name='service_container_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sandboxsession',
            name='service_ip',
            field=models.CharField(blank=True, help_text='IP of the scenario service container', max_length=45),
        ),
        migrations.AlterField(
            model_name='labprogress',
            name='stage',
            field=models.CharField(choices=[('theory', 'Theory'), ('sandbox', 'Sandbox'), ('challenge', 'Challenge'), ('complete', 'Complete')], max_length=32),
        ),
        migrations.CreateModel(
            name='FlagSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_flag', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_submissions', to='core.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='lab',
            name='scenario_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='core.scenarioservice'),
        ),
    ]
