# Generated by Django 6.0.6 on 2026-07-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_scenarioservice_lab_flag_lab_flag_hint_lab_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxsession',
            name='service_port',
            field=models.IntegerField(blank=True, help_text='External port mapped for the service container', null=True),
        ),
        migrations.AddField(
            model_name='scenarioservice',
            name='default_flag',
            field=models.CharField(blank=True, default='', help_text='The flag defined in the script, auto-populated when instructor selects this service.', max_length=500),
        ),
    ]
