# Generated by Django 6.0.6 on 2026-07-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sandboxsession_service_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='challenge_answer',
            field=models.CharField(blank=True, help_text='Correct answer (text for text answer, or full option text for multiple choice).', max_length=500),
        ),
        migrations.AddField(
            model_name='lab',
            name='challenge_options',
            field=models.TextField(blank=True, help_text='JSON array of answer options, e.g. ["Option A","Option B","Option C","Option D"]'),
        ),
        migrations.AddField(
            model_name='lab',
            name='challenge_question',
            field=models.TextField(blank=True, help_text='The question shown to students when challenge_type is Question.'),
        ),
        migrations.AddField(
            model_name='lab',
            name='challenge_type',
            field=models.CharField(choices=[('flag', 'Flag'), ('question', 'Question')], default='flag', help_text='Flag requires finding a hidden value. Question requires answering a quiz.', max_length=16),
        ),
    ]
