# Generated by Django 6.0.6 on 2026-07-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lab_challenge_answer_lab_challenge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxsession',
            name='terminal_port',
            field=models.IntegerField(blank=True, help_text='Port of per-sandbox ttyd instance', null=True),
        ),
    ]
