# Generated by Django 6.0.6 on 2026-07-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sandboxsession_terminal_port'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
