# Generated by Django 6.0.6 on 2026-07-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(help_text='Docker Hub image tag, e.g. ghostriley23/kali-ttyd:latest', max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('terminal', 'Browser terminal (ttyd)'), ('service', 'Vulnerable service')], max_length=16)),
                ('container_port', models.PositiveIntegerField(help_text='TCP port exposed inside the container (ttyd is usually 7681).')),
                ('description', models.TextField(blank=True)),
                ('command', models.CharField(blank=True, help_text='Optional command override, separated by spaces.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sandboxsession',
            name='network_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sandboxsession',
            name='service_container_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sandboxsession',
            name='service_endpoints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lab',
            name='service_containers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'service'}, related_name='service_labs', to='core.containerimage'),
        ),
        migrations.AddField(
            model_name='lab',
            name='terminal_container',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'terminal'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_labs', to='core.containerimage'),
        ),
        migrations.CreateModel(
            name='PortReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_reservations', to='core.sandboxsession')),
            ],
            options={
                'ordering': ['port'],
            },
        ),
    ]
