# Generated by Django 6.0.6 on 2026-07-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_containerimage_sandboxsession_network_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='scenario_service',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='sandbox_config',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='sandbox_image',
        ),
        migrations.DeleteModel(
            name='ScenarioService',
        ),
    ]
