# Generated by Django 4.2.30 on 2026-07-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_lab_scenario_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprofile',
            name='cpu_count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
