# Generated by Django 4.2.30 on 2026-07-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_resourceprofile_cpu_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('docker_node_id', models.CharField(blank=True, help_text='Swarm node ID', max_length=128)),
                ('public_ip', models.GenericIPAddressField(help_text='Student-facing IP for terminal URLs')),
                ('docker_host', models.CharField(help_text='Docker API endpoint, e.g. https://10.0.1.5:2376', max_length=256)),
                ('port_start', models.PositiveIntegerField(default=9000)),
                ('port_end', models.PositiveIntegerField(default=9100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draining', 'Draining'), ('offline', 'Offline')], default='active', max_length=20)),
                ('total_cpu', models.DecimalField(decimal_places=2, default=2, help_text='Total CPU cores on this node', max_digits=4)),
                ('total_memory_mb', models.PositiveIntegerField(default=2048, help_text='Total RAM in MB')),
                ('current_sessions', models.PositiveIntegerField(default=0, help_text='Active sandbox count')),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sandboxsession',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.dockernode'),
        ),
    ]
