# Generated by Django 4.2.30 on 2026-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dockernode_sandboxsession_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockernode',
            name='ssh_host',
            field=models.GenericIPAddressField(blank=True, default=None, help_text='SSH IP (defaults to public_ip)', null=True),
        ),
        migrations.AddField(
            model_name='dockernode',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='dockernode',
            name='ssh_user',
            field=models.CharField(default='ubuntu', max_length=64),
        ),
    ]
