# Generated by Django 4.2.30 on 2026-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dockernode_ssh_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockernode',
            name='setup_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dockernode',
            name='setup_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
