# Generated by Django 4.2.30 on 2026-07-26 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_dockernode_setup_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label, e.g. somacloud-prod', max_length=80, unique=True)),
                ('private_key', models.FileField(help_text='PEM-encoded private key file', upload_to='keys/')),
                ('fingerprint', models.CharField(blank=True, editable=False, help_text='SHA-256 fingerprint, auto-calculated', max_length=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dockernode',
            name='ssh_key',
            field=models.ForeignKey(blank=True, help_text='Pre-registered SSH key for setup', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sshkey'),
        ),
    ]
