# Generated by Django 6.0.6 on 2026-08-28 05:57

from django.db import migrations, models


def backfill_published_at(apps, schema_editor):
    Lab = apps.get_model("core", "Lab")
    Lab.objects.filter(is_published=True, published_at__isnull=True).update(published_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_loginlog_pageviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the lab was most recently published.', null=True),
        ),
        migrations.RunPython(backfill_published_at, migrations.RunPython.noop),
    ]
