# Generated by Django 6.0.6 on 2026-09-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_publish_lab_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='gui_ready',
            field=models.BooleanField(default=False, help_text='Whether sandboxes using this profile run a GUI desktop (VNC); the scheduler allocates more headroom for these.'),
        ),
    ]
