[kdcdefaults]
  kdc_ports = 88
  kdc_tcp_ports = 88

[realms]
  GLOBEX.LOCAL = {
    database_name = /var/kerberos/krb5kdc/principal
    admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
    acl_file = /var/kerberos/krb5kdc/kadm5.acl
    key_stash_file = /var/kerberos/krb5kdc/.k5.GLOBEX.LOCAL
    max_life = 10h
    max_renewable_life = 7d
    master_key_type = aes256-cts
    supported_enctypes = aes256-cts:normal aes128-cts:normal
    default_principal_flags = +preauth
  }