[libdefaults]
  default_realm = GLOBEX.LOCAL
  dns_lookup_realm = false
  dns_lookup_kdc = false
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true
  rdns = false

[realms]
  GLOBEX.LOCAL = {
    kdc = localhost:88
    admin_server = localhost:749
  }

[domain_realm]
  globex.local = GLOBEX.LOCAL
  .globex.local = GLOBEX.LOCAL