server {
    listen 80 default_server;
    server_name _;
    root /srv/www;
    index index.html;

    add_header X-Powered-By "PHP/8.2.3" always;
    add_header X-Generator "GlobexCMS 3.1" always;

    location = /robots.txt { }

    location /private/ {
        autoindex on;
        autoindex_exact_size off;
    }

    location /backup/ {
        autoindex on;
        autoindex_exact_size off;
    }

    location /admin/ {
        return 403;
    }

    location /server-status {
        return 403;
    }
}