modulepath /usr/lib/openldap
moduleload back_mdb

include  /etc/openldap/schema/core.schema
include  /etc/openldap/schema/cosine.schema
include  /etc/openldap/schema/inetorgperson.schema
include  /etc/openldap/schema/nis.schema

pidfile  /run/slapd.pid
argsfile /run/slapd.args

database  mdb
suffix    "dc=globex,dc=local"
rootdn    "cn=admin,dc=globex,dc=local"
rootpw    GlobexRoot@2026
directory /var/lib/ldap

index objectClass,uid,cn eq

access to * by * read